
clean: clean-both

clean-both:
    cd host && cargo clean --target-dir ../target
    cd guest && cargo clean --target-dir ../target

build-guest:
    cd guest && cargo build --target-dir ../target --target=x86_64-unknown-none

build-host:
    cd host && cargo build --target-dir ../target
