[package]
name = "helloworld_guest"
version = "0.0.1"
edition = "2021"

[dependencies]
hyperlight-guest = { version="0.4.0" }
hyperlight-common = { version="0.4.0", default-features = false }

[profile.release]
debug = true
